# Generated by Django 3.2.7 on 2021-10-11 19:43

import Gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': 'Képek'},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='visible',
            new_name='homepage',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=Gallery.models.image_dir_path),
        ),
    ]
