# Generated by Django 3.2.7 on 2021-10-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_auto_20211011_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
