# Generated by Django 3.2.7 on 2021-10-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_aboutpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name_plural': 'About page info'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name_plural': 'Home page info'},
        ),
        migrations.AlterModelOptions(
            name='pageinfo',
            options={'verbose_name_plural': 'Oldal info'},
        ),
    ]
